module.exports = {
  AddProductPage: {
    new_product_button: '#page-header-desc-configuration-add',
    product_name_input: '#form_step1_name_1',
    picture: '[class="dz-hidden-input"]',
    product_reference_input: '//*[@id="form_step6_reference"]',
    quantity_shortcut_input: '#form_step1_qty_0_shortcut',
    priceTE_shortcut: '#form_step1_price_shortcut',
    priceTTC_shortcut: '#form_step1_price_ttc_shortcut',
    tax_rule_select: '#select2-step2_id_tax_rules_group_rendered-container',
    tax_rule_option: '//*[@id="select2-step2_id_tax_rules_group_rendered-results"]/li[%I]', // %I = 3 : Tax 10%
    quantities_link: '//*[@id="product_qty_0_shortcut_div"]//a[text()="Quantities"]',
    product_quantity_input: '//*[@id="form_step3_qty_0"]',
    basic_settings_tab: '//*[@id="tab_step1"]/a',
    pricing_link: '//*[@id="step1"]//a[@href="#tab-step2" and text()="Pricing"]',
    pricing_wholesale: '//*[@id="form_step2_wholesale_price"]',
    summary_textarea: '(//*[@id="form_step1_description_short"]//div[@class="mce-tinymce mce-container mce-panel"])[1]',
    description_textarea: '(//*[@id="form_step1_description"]//div[@class="mce-tinymce mce-container mce-panel"])[1]',
    product_online_toggle: '.switch-input ',
    preview_buttons: '//*[@id="product_form_preview_btn"]',
    add_feature_to_product_button: '//*[@id="add_feature_button"]',
    feature_select: '//*[@id="select2-form_step1_features_%ID_feature-container"]',
    feature_select_option: '//*[@id="select2-form_step1_features_%ID_feature-results"]/li[text()="%V"]',
    feature_custom_value: '//*[@id="form_step1_features_%ID_custom_value_1"]',
    feature_value_select: '//*[@id="form_step1_features_%ID_value"]',
    delete_feature_icon: '(//*[@id="features-content"]//a[contains(@class, "delete")]/i[text()= "delete"])[%POS]',
    delete_confirmation_button: '//*[@id="confirmation_modal"]//button[contains(text(), "Yes")]',
    add_brand_button: '//*[@id="add_brand_button"]',
    product_brand_select: '//*[@id="manufacturer-content"]/div/div[1]/fieldset/span',
    product_brand_select_option: '//*[@id="select2-form_step1_id_manufacturer-results"]/li[2]',
    delete_brand_icon: '//*[@id="reset_brand_product"]',
    category_expand_button: '//*[@id="categories"]//span[@data-action="expand"]',
    catalog_home: '//*[@id="form_step1_categories"]/ul/li/div/label',
    catalog_element_radio: '//*[@id="form_step1_categories"]/ul/li/ul/li[%I]/div',
    create_category_button: '//*[@id="add-category-button"]',
    product_category_name_input: '//*[@id="form_step1_new_category_name"]',
    parent_category_select: '//*[@id="select2-form_step1_new_category_id_parent-container"]',
    parent_category_search_input: '//input[@type="search" and contains(@class, "select2-search")]',
    parent_category_option: '//*[@id="select2-form_step1_new_category_id_parent-results"]/li[text()="%N"]',
    category_save_button: '//*[@id="form_step1_new_category_save"]',
    category_checkbock: '//*[@id="form_step1_categories"]//label[text()[contains(.,"%S")]]/input[1]',
    home_delete_button: '//*[@id="ps_categoryTags"]/span[1]/a',
    delete_category_icon: '//*[@id="ps_categoryTags"]/span[%I]/a',
    add_related_product_btn: '//*[@id="add-related-product-button"]',
    search_add_related_product_input: '//*[@id="form_step1_related_products"]',
    related_product_item: '//*[@id="related-content"]/div[2]/fieldset/div/div[1]/span/div/div/div[1]',
    delete_related_product_icon: '//*[@id="reset_related_product"]',
    product_quantities_tab: '//*[@id="tab_step3"]/a',
    minimum_quantity_sale_input: '//*[@id="form_step3_minimal_quantity"]',
    availability_preferences_radio_button: '//*[@id="form_step3_out_of_stock_%I"]',
    label_in_stock_input: '//*[@id="form_step3_available_now_1"]',
    label_out_stock_input: '//*[@id="form_step3_available_later_1"]',
    availability_date_input: '//*[@id="form_step3_available_date"]',
    low_stock_level_checkbox: '//*[@id="form_step3_low_stock_alert"]',
    low_stock_level_input: '//*[@id="form_step3_low_stock_threshold"]',
    product_shipping_tab: '//*[@id="tab_step4"]/a',
    shipping_width: '//*[@id="form_step4_width"]',
    shipping_height: '//*[@id="form_step4_height"]',
    shipping_depth: '//*[@id="form_step4_depth"]',
    shipping_weight: '//*[@id="form_step4_weight"]',
    shipping_fees: '//*[@id="form_step4_additional_shipping_cost"]',
    shipping_available_carriers: '//*[@id="form_step4_selectedCarriers_%I"]',
    product_pricing_tab: '//*[@id="tab_step2"]/a',
    product_pricing_ttc_input: '//*[@id="form_step2_price_ttc"]',
    product_pricing_ht_input: '//*[@id="form_step2_price"]',
    pricing_tax_rule_select: '//*[@id="step2"]/div/div/div/div/div[3]/div/div[1]/span',
    pricing_tax_rule_input: '//span[contains(@class, "select2-search")]/input[@type="search"]',
    pricing_tax_rule_option: '//*[@id="select2-form_step2_id_tax_rules_group-results"]/li[contains(text(), "%T")]',
    pricing_manage_tax_rules_link: '//*[@id="step2"]//a[contains(text(), "Manage tax rules")]',
    unit_price: '#form_step2_unit_price',
    unity: '#form_step2_unity',
    on_sale_checkbox: '#form_step2_on_sale',
    pricing_add_specific_price_button: '//*[@id="specific-price"]/a',
    specific_price_starting_at_input: '//*[@id="form_step2_specific_price_sp_from_quantity"]',
    leave_initial_price_checkbox: '//*[@id="form_step2_specific_price_leave_bprice"]',
    specific_product_price_input: '//*[@id="form_step2_specific_price_sp_price"]',
    specific_price_reduction_type_select: '//*[@id="form_step2_specific_price_sp_reduction_type"]',
    specific_price_reduction_tax_select: '//*[@id="form_step2_specific_price_sp_reduction_tax"]',
    specific_price_discount_input: '//*[@id="form_step2_specific_price_sp_reduction"]',
    specific_price_save_button: '//*[@id="form_step2_specific_price_save"]',
    specific_price_delete_icon: '//*[@id="js-specific-price-list"]//a/i[text()="delete"]',
    specific_price_available_from_input: '//*[@id="form_step2_specific_price_sp_from"]',
    specific_price_to_input: '//*[@id="form_step2_specific_price_sp_to"]',
    specific_price_customer_input: '//*[@id="form_step2_specific_price_sp_id_customer"]',
    specific_price_customer_option: '//*[@id="specific_price_form"]//div[contains(@class, "tt-menu")]',
    specific_price_leave_initial_price_input: '//*[@id="form_step2_specific_price_leave_bprice"]',
    specific_price_impact_on_price_input: '//*[@id="form_step2_specific_price_sp_price"]',
    specific_price_for_currency_select: '//*[@id="select2-form_step2_specific_price_sp_id_currency-container"]',
    specific_price_for_currency_option: '//*[@id="select2-form_step2_specific_price_sp_id_currency-results"]/li[text()="%C"]',
    specific_price_for_country_select: '//*[@id="select2-form_step2_specific_price_sp_id_country-container"]',
    specific_price_for_country_search_input: '//span[contains(@class, "select2-search")]/input[@type="search"]',
    specific_price_for_country_option: '//*[@id="select2-form_step2_specific_price_sp_id_country-results"]/li[text()="%C"]',
    specific_price_for_group_select: '//*[@id="select2-form_step2_specific_price_sp_id_group-container"]',
    specific_price_for_group_option: '//*[@id="select2-form_step2_specific_price_sp_id_group-results"]/li[text()="%C"]',
    product_SEO_tab: '//*[@id="tab_step5"]/a',
    SEO_meta_title: '//*[@id="form_step5_meta_title_1"]',
    SEO_meta_description: '//*[@id="form_step5_meta_description_1"]',
    SEO_friendly_url: '//*[@id="form_step5_link_rewrite_1"]',
    product_options_tab: '//*[@id="tab_step6"]/a',
    options_online_only: '//*[@id="form_step6_display_options_online_only"]',
    options_available_for_order_checkbox: '//*[@id="form_step6_display_options_available_for_order"]',
    options_show_price_checkbox: '//*[@id="form_step6_display_options_show_price"]',
    options_visibility: '//*[@id="form_step6_visibility"]',
    options_show_condition_checkbox: '//*[@id="form_step6_show_condition"]',
    options_condition_select: '//*[@id="form_step6_condition"]',
    options_isbn: '//*[@id="form_step6_isbn"]',
    options_ean13: '//*[@id="form_step6_ean13"]',
    options_upc: '//*[@id="form_step6_upc"]',
    options_add_customization_field_button: '//*[@id="custom_fields"]/a',
    options_first_custom_field_label: '//*[@id="form_step6_custom_fields_0_label_1"]',
    options_first_custom_field_type: '//*[@id="form_step6_custom_fields_0_type"]',
    options_first_custom_field_require: '//*[@id="form_step6_custom_fields_0_require"]',
    options_second_custom_field_label: '//*[@id="form_step6_custom_fields_1_label_1"]',
    options_second_custom_field_type: '//*[@id="form_step6_custom_fields_1_type"]',
    delete_customization_field_icon: '//*[@id="custom_fields"]//a[contains(@class, "delete")]',
    options_add_new_file_button: '//*[@id="step6"]/div/div/div/div/div/div[11]/div/a',
    options_select_file: '//*[@id="form_step6_attachment_product_file"]',
    options_file_name: '//*[@id="form_step6_attachment_product_name"]',
    options_file_description: '//*[@id="form_step6_attachment_product_description"]',
    options_file_add_button: '//*[@id="form_step6_attachment_product_add"]',
    options_file_checkbox: '//*[@id="form_step6_attachments_0"]',
    attached_file_checkbox: '//*[@id="product-attachment-file"]/tbody//label[contains(text(),"%FileName")]/input',
    click_outside: '//*[@id="product_catalog_list"]/div[2]/div/table/thead/tr[1]/th[3]',
    go_to_catalog_button: '#form > div.product-footer.justify-content-md-center > div.col-sm-5.col-lg-7.text-right > div.btn-group.hide.dropdown.show > div > a.dropdown-item.go-catalog.js-btn-save',
    new_product_dropdown_button: '#form > div.product-footer.justify-content-md-center > div.col-sm-5.col-lg-7.text-right > div.btn-group.hide.dropdown.show > div > a.dropdown-item.new-product.js-btn-save',
    more_option_button: '.btn.btn-primary.dropdown-toggle',
    save_product_button: '//*[@id="form"]/div[4]/div[2]/div/button[1]',
    green_validation_notice: '[class="growl growl-notice growl-medium"]',
    close_validation_button: '.growl-close',
    validation_msg: '#growls-default > .growl-notice > .growl-message:not(:empty)',
    red_validation_notice: '[class="growl growl-error growl-medium"]',
    description_tab: '[href="#description"]',
    picture_cover: '.iscover',
    catalogue_filter_by_name_input: '//input[@name="filter_column_name"]',
    catalogue_submit_filter_button: '//button[@name="products_filter_submit"]',
    variations_type_button: '//*[@id="show_variations_selector"]/div[2]/label/input',
    product_combinations_tab: '//*[@id="tab_step3"]/a',
    product_combinations: '//*[@id="show_variations_selector"]/div[%I]/label/input',
    variations_input: '//*[@id="form_step3_attributes-tokenfield"]',
    variations_generate: '//*[@id="create-combinations"]',
    variations_select: '//*[@id="attributes-generator"]/div[2]/div[1]/fieldset/div/span/div/div/div',
    var_selected: '//*[@id="toggle-all-combinations"]',
    var_selected_quantitie: '//*[@id="product_combination_bulk_quantity"]',
    combinations_thead: '//*[@id="combinations_thead"]/tr/th[7]',
    save_quantitie_button: '//*[@id="apply-on-combinations"]',
    select_feature_created: '/html/body//span/span[1]/input',
    feature_select_button: '//*[@id="features-content"]/div/div/div[1]/fieldset/span/span[1]/span',
    result_feature_select: '//*[@id="select2-form_step1_features_%ID_feature-results"]/li',
    tab_description: '//*[@id="tab_description"]/a',
    product_type: '#form_step1_type_product',
    search_product_pack: '//*[@id="form_step1_inputPackItems"]',
    product_item_pack: '//*[@id="js_form_step1_inputPackItems"]/div/div[1]/span/div/div/div[1]/table/tbody/tr[1]',
    product_pack_item_quantity: '//*[@id="form_step1_inputPackItems-curPackItemQty"]',
    product_pack_add_button: '//*[@id="form_step1_inputPackItems-curPackItemAdd"]',
    product_add_feature_btn: '//*[@id="add_feature_button"]',
    pack_stock_type: '//*[@id="form_step3_pack_stock_type"]',
    virtual_associated_file: '#form_step3_virtual_product_is_virtual_file_0',
    virtual_select_file: '#form_step3_virtual_product_file',
    virtual_file_name: '#form_step3_virtual_product_name',
    virtual_file_number_download: '#form_step3_virtual_product_nb_downloadable',
    virtual_expiration_file_date: '#form_step3_virtual_product_expiration_date',
    virtual_number_days: '#form_step3_virtual_product_nb_days',
    virtual_save_attached_file: '#form_step3_virtual_product_save',
    combination_size_s: '//*[@id="attribute-group-1"]//label[@for="attribute-1"]',
    combination_size_m: '//*[@id="attribute-group-1"]//label[@for="attribute-2"]',
    combination_color_grey: '//*[@id="attribute-group-2"]//label[@for="attribute-5"]',
    combination_color_beige: '//*[@id="attribute-group-2"]//label[@for="attribute-7"]',
    combination_color_green: '//label[@for="attribute-15"]',
    combination_color_red: '//label[@for="attribute-10"]',
    combination_generate_button: '//*[@id="create-combinations"]',
    combination_impact_price_input: '//*[@id="attribute_%NUMBER"]/td[@class="attribute-price"]//input',
    combination_final_price_span: '//*[@id="attribute_%NUMBER"]/td[contains(@class, "attribute-finalprice")]/span',
    combination_panel: '//*[@id="accordion_combinations"]/tr[%NUMBER]',
    combination_quantity: '//*[@id="combination_%NUMBER_attribute_quantity"]',
    combination_available_date: '//*[@id="combination_%NUMBER_available_date_attribute"]',
    combination_min_quantity: '//*[@id="combination_%NUMBER_attribute_minimal_quantity"]',
    combination_reference: '//*[@id="combination_%NUMBER_attribute_reference"]',
    combination_whole_sale: '//*[@id="combination_%NUMBER_attribute_wholesale_price"]',
    combination_low_stock: '//*[@id="combination_%NUMBER_attribute_low_stock_threshold"]',
    combination_priceTI: '//*[@id="combination_%NUMBER_attribute_priceTI"]',
    combination_attribute_unity: '//*[@id="combination_%NUMBER_attribute_unity"]',
    combination_attribute_weight: '//*[@id="combination_%NUMBER_attribute_weight"]',
    combination_attribute_isbn: '//*[@id="combination_%NUMBER_attribute_isbn"]',
    combination_attribute_ean13: '//*[@id="combination_%NUMBER_attribute_ean13"]',
    combination_attribute_upc: '//*[@id="combination_%NUMBER_attribute_upc"]',
    combination_attribute_image: '//*[@id="attribute_%NUMBER"]/td[2]/img',
    combination_attribute_quantity: '//*[@id="attribute_%NUMBER"]/td[6]/div/input',
    combination_image: '//*[@id="combination_%NUMBER_id_image_attr"]/div[2]/img',
    combination_edit: '//*[@id="attribute_%NUMBER"]/td[7]/div[1]/a',
    combination_default_button: '//input[@class="attribute-default" and @data-id="%NUMBER"]',
    default_combination: '//*[@id="combination_%NUMBER_attribute_default"]',
    back_to_product: '//*[@id="combination_form_%NUMBER"]/div[2]/div[1]/button',
    pricing_first_priorities_select: '//*[@id="form_step2_specificPricePriority_0"]',
    pricing_second_priorities_select: '//*[@id="form_step2_specificPricePriority_1"]',
    pricing_third_priorities_select: '//*[@id="form_step2_specificPricePriority_2"]',
    pricing_fourth_priorities_select: '//*[@id="form_step2_specificPricePriority_3"]',
    catalog_product_table: '#product_catalog_list table.product',
    get catalog_product_name() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(4) > a';
    },
    get catalog_product_reference() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(5)';
    },
    get catalog_product_category() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(6)';
    },
    get catalog_product_price() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(7)';
    },
    get catalog_product_quantity() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(8)';
    },
    get catalog_product_online() {
      return this.catalog_product_table + ' > tbody tr:first-child > td:nth-child(9) > a > i';
    },
    get catalog_reset_filter() {
      return this.catalog_product_table + ' .column-filters button[name="products_filter_reset"]';
    },
    get catalog_submit_filter() {
      return this.catalog_product_table + '.column-filters button[name="products_filter_submit"]';
    },
    category_radio_button: '//*[@id="form_step1_categories"]//input[@name="ignore" and @value="%VALUE"]',
    category_radio: '//*[@id="form_step1_categories"]//label[text()[contains(.,"%S")]]/input[2]',
    dropdown_button: '//*[@id="dropdownMenu"]',
    duplicate_button: '//*[@aria-labelledby="dropdownMenu"]//a[contains(@class, "duplicate")]',
    success_panel: '//div[contains(@class, "alert-success")]//p',
    delete_button: '//*[@id="product_form_delete_btn"]',
    symfony_toolbar: '//*[contains (@id, "sfToolbarMainContent")]/a',
    summary_tinymce_buttons: '//*[@id="description_short"]//div[contains(@class, "mce-toolbar-grp")]',
    combination_first_table: '//*[@id="accordion_combinations"]',
    combination_second_table: '//*[@id="accordion_combinations"]//tr[2]',
    created_category: '//*[@id="ps_categoryTags"]/span[2]/span',
    preview_link: '//a',
    continue_confirmation: '//*[@id="confirmation_modal"]//button[2]',
    search_categories: '//*[@id="ps-select-product-category"]',
    list_categories: '//*[@id="ui-id-1"]/li',
    default_category: '//*[@id="ps_categoryTags"]/span[1]/a',
    image_combination_src: '(//*[@id="combination_%ID_id_image_attr"]//img)[%POS]',
    img_added_product_pack: '//*[@id="form_step1_inputPackItems-data"]/li[%ID]//img',
    product_type_option: '//*[@id="form_step1_type_product"]/option[%POS]',
    tax_rule_taux_standard_option: '//*[@id="step2_id_tax_rules_group_rendered"]/option[5]',
    predefined_value_option: '//*[@id="form_step1_features_0_value"]/option[text()="%V"]',
    custom_value_input: '//*[@id="form_step1_features_0_custom_value_1"]',
    background_picture: '//*[@id="product-images-dropzone"]//div[@class="dz-image bg"]',
    product_pack_items: '//*[@id="form_step1_inputPackItems-data"]',
    add_products_to_pack: '//*[@id="js_form_step1_inputPackItems"]/div'
  },
  ProductList: {
    product_id: '//*[@id="product_catalog_list"]//tr[%ID]/td[2]/label',
    product_name: '//*[@id="product_catalog_list"]//tbody/tr[%ID]/td[4]/a',
    product_reference: '//*[@id="product_catalog_list"]//tbody/tr[%ID]/td[5]',
    sort_by_icon: '//*[@id="product_catalog_list"]//div[@data-sort-col-name="%B" and @data-sort-direction="%W"]/span[@role="button"]',
    sort_button: '//*[@id="product_catalog_list"]//div[@data-sort-col-name="%B"]/span[@role="button"]',
    status_select: '//*[@id="product_filter_column_active"]//select[@name="filter_column_active"]',
    product_status: '//*[@id="product_catalog_list"]//tr[%I]/td[9]/a/i[contains(@class, "action-%ACTION")]',
    edit_button: '//*[@id="product_catalog_list"]//i[text()="mode_edit"]',
    pagination_products: '//*[@id="product_catalog_list"]//div[contains(@class, "justify-content-center")]/div[1]',
    dropdown_button: '(//*[@id="product_catalog_list"]//tbody//div[@class="btn-group-action"]//button[@data-toggle="dropdown"])[%POS]',
    action_preview_button: '(//*[@id="product_catalog_list"]//tbody//div[@class="btn-group-action"]//a[contains(@target,"_blank")])[%POS]',
    action_duplicate_button: '(//*[@id="product_catalog_list"]//tbody//div[@class="btn-group-action"]//a[contains(@onclick,"duplicate")])[%POS]',
    action_delete_button: '(//*[@id="product_catalog_list"]//tbody//div[@class="btn-group-action"]//a[contains(@onclick,"delete")])[%POS]',
    delete_now_modal_button: '//*[@id="catalog_deletion_modal"]//button[contains(text(), "Delete now")]',
    search_no_results: '//*[@id="product_catalog_list"]//tbody/tr[1]/td',
    pagination_next: '//*[@id="pagination_next_url"]',
    pagination_previous: '//*[@id="product_catalog_list"]//li[@class="page-item previous "]//a',
    page_active_number: '//*[@id="product_catalog_list"]//li[@class="page-item active"]//input',
    item_per_page: '//*[@id="paginator_select_page_limit"]',
    product_category: '//*[@id="product_catalog_list"]//div//tr[%I]/td[6]',
    reset_button: '//*[@id="product_catalog_list"]//tr[2]/th[9]/button[@name="products_filter_reset"]',
    status_filter: '//*[@id="product_filter_column_active"]//select[@name=\'filter_column_active\']',
    item_per_page_select: '//*[@id="paginator_select_page_limit"]'
  }
};
